Repository ComposioHQ/docs, pull requests merged in 2024-06, with the labels that each got.

#20 Local Tool docs
  mint.json
  sdk/python/local_tools.mdx
Labels: documentation, Review effort [1-5]: 2

#21 Enhancements: Consistency in codes across the docs.
  apps/list.mdx
  framework/autogen.mdx
  framework/crewai.mdx
  framework/griptape.mdx
  framework/julep.mdx
  framework/langchain.mdx
  framework/lyzr.mdx
  framework/openai.mdx
  guides/examples/CompetitorResearcher.mdx
  guides/examples/Example.mdx
  guides/examples/InvestmentAnalyst.mdx
  guides/examples/ResearchAssistant.mdx
  guides/examples/github-trello.mdx
  guides/examples/news-summary.mdx
  guides/examples/todo-to-calendar.mdx
  guides/examples/urlsummary.mdx
  introduction/foundations/basic.mdx
  introduction/foundations/components/actions/action-guide.mdx
  introduction/foundations/components/entity/entity-guide.mdx
  introduction/foundations/components/triggers/trigger-guide.mdx
  introduction/intro/quickstart.mdx
  mint.json
  sdk/python/actions.mdx
  sdk/python/configuration.mdx
Labels: documentation, enhancement, Review effort [1-5]: 3

#22 Changes: Repo name changes And Tools Page changes
  apps/list.mdx
  framework/autogen.mdx
  framework/crewai.mdx
  framework/griptape.mdx
  framework/julep.mdx
  framework/langchain.mdx
  framework/lyzr.mdx
  framework/openai.mdx
  introduction/foundations/components/entity/entity-guide.mdx
  introduction/intro/quickstart.mdx
Labels: documentation, Review effort [1-5]: 2

#26 Update QuickStart guide
  introduction/intro/quickstart.mdx
Labels: documentation, Review effort [1-5]: 1

#31 Improvements/29. Core Concepts page and Tools page have been changed.
  apps/list.mdx
  guides/examples/Example.mdx
  guides/examples/calendar-agent.mdx
  guides/examples/commit-agent.mdx
  guides/examples/competitor-researcher.mdx
  guides/examples/investment-analyst.mdx
  guides/examples/news-summary.mdx
  guides/examples/research-assistant.mdx
  guides/examples/sql-agent.mdx
  introduction/foundations/basic.mdx
  introduction/foundations/components/integrations/custom-integration.mdx
  introduction/foundations/tools/category/codeinterpreter.mdx
  introduction/foundations/tools/category/searchtools.mdx
  introduction/foundations/tools/category/softwaretools.mdx
  introduction/foundations/tools/category/systemtools.mdx
  introduction/foundations/tools/tools-intro.mdx
  mint.json
Labels: documentation, enhancement, Review effort [1-5]: 3

#36 Enhancements: Rag and codeinterpreter
  guides/examples/sql-agent.mdx
  introduction/foundations/tools/category/codeinterpreter.mdx
  introduction/foundations/tools/category/ragtools.mdx
  introduction/foundations/tools/tools-intro.mdx
Labels: documentation, enhancement, Review effort [1-5]: 2

#37 Added simple coding guides for rag tool and code interpreter tool
  guides/examples/commit-agent.mdx
  guides/examples/interpreter_agent.mdx
  guides/examples/qnasummary.mdx
  guides/examples/rag_agent.mdx
  guides/examples/sql-agent.mdx
  introduction/foundations/tools/category/ragtools.mdx
  mint.json
Labels: documentation, enhancement, Review effort [1-5]: 3
