Repository ComposioHQ/docs, pull requests merged in 2024-05, with the labels that each got.

#11 update backlink
  introduction/intro/resources/ai.mdx
  mint.json
Labels: enhancement, configuration changes, Review effort [1-5]: 2

#13 misc
  introduction/intro/resources/ai.mdx
Labels: documentation, Review effort [1-5]: 1

#14 add startups program, update pricing page
  introduction/pricing/pricing.mdx
  introduction/pricing/startups-program.mdx
  mint.json
Labels: documentation, enhancement, Review effort [1-5]: 2

#19 Bugs fixed
  guides/examples/CompetitorResearcher.mdx
  guides/examples/InvestmentAnalyst.mdx
  guides/examples/ResearchAssistant.mdx
  guides/examples/github-trello.mdx
  guides/examples/news-summary.mdx
  guides/examples/todo-to-calendar.mdx
  guides/examples/urlsummary.mdx
Labels: Review effort [1-5]: 2, Bug fix
